### PR TITLE
Add missing properties to SalesInvoice model

### LINKED ISSUE #186: Add missing properties to SalesInvoice model
The Moneybird API [returns some fields](https://developer.moneybird.com/api/sales_invoices/#get_sales_invoices_id) that aren't in the SalesInvoice model of this library:

- administration_id
- recurring_sales_invoice_id
- draft_id
- paused
- payment_reference
- total_unpaid_base
- total_discount
- events
- tax_totals

I'll provide a PR shortly that adds these fields to the SalesInvoice Model.

### PR DESCRIPTION
**Pull request by dennisameling**
Closes #186 and updates Travis config to switch to Trusty for PHP 5.* support

### CODE REVIEW

**Comment by stephangroen** [comment]
Thanks! Can you add the new entity to https://github.com/picqer/moneybird-php-client/blob/master/tests/EntityTest.php?

**Comment by dennisameling** [comment]
@stephangroen Done, but the TravisCI build isn't working on PHP 5.5. Seems like this is a known problem that can be fixed by switching from `Xenial` to `Trusty` in the `.travis.yml`: https://travis-ci.community/t/php-5-4-and-5-5-archives-missing/3723/6.

I'm happy to add a commit for `.travis.yml` to this PR, but only if that's OK for you.

**Comment by stephangroen** [comment]
> I'm happy to add a commit for .travis.yml to this PR, but only if that's OK for you.

That's OK, would be great actually. Will merge after that.

**Comment by dennisameling** [comment]
> > I'm happy to add a commit for .travis.yml to this PR, but only if that's OK for you.
> 
> That's OK, would be great actually. Will merge after that.

I added it to the `travis.yml` file, but Travis still takes the `travis.yml` from your [master](https://github.com/picqer/moneybird-php-client/blob/master/.travis.yml) instead of the one in my PR. So you either would need to update it on master yourself (if you want to be 100% sure that the tests will pass), or merge my PR so that the `travis.yml` in master is updated. Thanks in advance :)

image

image

**Comment by dennisameling** [comment]
> > I'm happy to add a commit for .travis.yml to this PR, but only if that's OK for you.
> 
> That's OK, would be great actually. Will merge after that.

Done :)

**Pull request merged**
