### PR TITLE
fix #144

### LINKED ISSUE #144: search contact
Hi,

How can we search for contact based on lastname or companyname?  I want to avoid having multiple contact with the same name. 

What is the best practice here?

Should be possible, based on: https://developer.moneybird.com/api/contacts/#get_contacts

Thank,
Roy

### PR DESCRIPTION
**Pull request by roydekleijn**
Fixes #144: We can now search on fields.

### CODE REVIEW

**Comment by stephangroen** [comment]
Thanks @roydekleijn

**Comment by roydekleijn** [comment]
welcome, but how / when does that end up in composer ?

**Comment by stephangroen** [comment]
Probably next week. I need to check on the other PR's and try to get them in as well.

**Comment by stephangroen** [comment]
Done :)

**Pull request merged**
