### PR TITLE
Add LedgerAccountBooking Entity

### PR DESCRIPTION
**Pull request by holtkamp**

### CODE REVIEW

**Comment by holtkamp** [comment]
@stephangroen thanks for merging! Would you consider tagging a new minor release, so I can get rid of my own branche 😉

**Comment by stephangroen** [comment]
On the way :)

**Comment by holtkamp** [comment]
Nice! 

FYI, I contacted Moneybird to request support for an endpoint to remove/unlink a LedgerAccountBooking using the API.

This can currently only be done using the GUI, which invokes endpoint:

`
https://moneybird.com/<administrationId>/financial_mutations/<financialMutationId>/unlink_booking/ledger_account_booking/<ledgerAccountBookingId>
`

Moneybird acknowledged the added value of this request and intends to enable this for the API 🤓

**Comment by holtkamp** [comment]
>I contacted Moneybird to request support for an endpoint to remove/unlink a LedgerAccountBooking using the API.

@stephangroen Moneybird just informed me the endpoint was added: https://developer.moneybird.com/api/financial_mutations/#delete_financial_mutations_id_unlink_booking

Will try to find some time to come up with a pull request for this coming week.

**Comment by stephangroen** [comment]
That's fast. 

>Will try to find some time to come up with a pull request for this coming week.

Always welcome :)

**Pull request merged**
