### PR TITLE
update checkWhetherRateLimitHasBeenReached

### PR DESCRIPTION
**Pull request by gldrenthe89**
updated checkWhetherRateLimitHasBeenReached for new behaviour of Moneybird API [throttling](https://developer.moneybird.com/#throttling) headers

### CODE REVIEW

**Comment by gldrenthe89** [comment]
Why is this not merged yet ??

**Comment by stephangroen** [comment]
Because tests are failing.

**Comment by gldrenthe89** [comment]
> Because tests are failing.

issues resolved

**Comment by gldrenthe89** [comment]
Issues have now been resolved correctly. please merge

**Pull request closed without merging**
