### PR TITLE
Moneybird expects numbered objects instead of arrays in json body. 

### PR DESCRIPTION
**Pull request by jorisleker**
Moneybird API expects numbered objects instead of arrays in json body of post requests.
(See [example request in documentation](http://developer.moneybird.com/api/sales_invoices/#post_sales_invoices_example0))

This pull request adds JSON_FORCE_OJBECT when encoding to json

### CODE REVIEW

**Comment by stephangroen** [comment]
Have you checked this for every possible API call? I ran into some issues and mentioned them to Moneybird, because (back then) this was not consistent throughout the API.

**Comment by jorisleker** [comment]
Ran it against SalesInvoices (get/find/create/update/sync), SalesInvoiceDetails, SalesInvoicePayments and the currently unsupported SalesInvoiceCustomFields. Last one _needs_ numbered objects to be passed, will fail otherwise. First three still work when passing object instead of array. Any specific ones you ran into trouble with previously?

**Comment by stephangroen** [comment]
I don't exactly know anymore, but I did play with the `JSON_FORCE_OBJECT` flag, which for some cases didn't work. Can you resolve the conflicts? I'll do some tests of my own and if they're OK, I'll be happy to merge!

**Comment by jorisleker** [comment]
done!

**Comment by stephangroen** [comment]
Thank you @jorisleker !

**Pull request merged**
