### PR TITLE
Change snake_cased BookingTypes to CamelCased BookingTypes

### PR DESCRIPTION
**Pull request by holtkamp**
As announced in https://github.com/picqer/moneybird-php-client/pull/154#issuecomment-403402721

### CODE REVIEW

**Comment by holtkamp** [comment]
@stephangroen did you notice this PR? 🤓

**Comment by stephangroen** [comment]
It's on my todo list but delayed to investigate the failing tests :)

**Comment by holtkamp** [comment]
aah, it seems I did not update the test, facepalm!

**Comment by holtkamp** [comment]
@stephangroen thanks for merging, can you tag a new release so I can get rid of my own branch? Probably `0.18.1`?

**Comment by stephangroen** [comment]
Done

**Pull request merged**
