### PR TITLE
replace deprecated parse_header with Header::parse

### PR DESCRIPTION
**Pull request by rikivesa**

### CODE REVIEW

**Comment by rikivesa** [comment]
@casperbakker Can you merge this PR?

**Comment by casperbakker** [comment]
@rikivesa Would love to, but please provide some more information about the change. Why is it needed? What version of dependencies do we not support anymore or which new version do we support now? Etc.

**Comment by rikivesa** [comment]
Same story as the previous PR (241): parse_header will be removed in guzzlehttp/psr7:2.0. Usage of Header::parse is adviced instead.

https://docs.aws.amazon.com/aws-sdk-php/v3/api/function-GuzzleHttp.Psr7.parse_header.html

**Comment by casperbakker** [comment]
#241

**Comment by casperbakker** [comment]
@rikivesa Thanks

**Pull request merged**
